language: java
notifications:
  email: false
  slack:
    secure: k3yyWHpMismLok/4nlnVUObeerA+zZRl/EPjL7rtmbwMB4Q6m4X1lPUjYVyYjXWAtUF5U5VjY5ORTf6pmXS0BnJ4fS/t3n7KJ0n7eL7Rphwq9UGWexXQ3KD2pDLL2Py29KZwprsYfqE+7CLo7To4anC9CY4reLxSXjy8a6WZ70RrBWlrZRYWq9cbxtCTFknHucVY1okApoS2DK8ZTYLnLxmzFXpktciDPHedzGLLJWM03JZSeOxok4N9/xPKHVIIffDcPzCjOyzzpqHEcJ846G2DLfX05kL1Y1kGnlku4MP3Vbx+qiqQKR2P7SL/nGyd2hJgqjKgeVlGX8fo7oZXdRA6iNCAkH9UnJ0KZA1OKA2h0DW3te2hhDsqeJzk0ka2GcvLrrpMlc1BG09Ssr2fbHbPc2UmyIFg7shLgS4b26wK7Fd2ecSvhLmZ/wTwMLlL4iakabaL6d7sFq9KGeCkQodqpzOxlgeltPszqrEpqIPCarMSwILaqedaHVoG4WXuIlPDHt8JnGK6xKnYynBJTvjcIL+w+sx07WD0HnNg2RDibY3bKu52RJf83XN5VWTrXarLGfN3h1lnwT7zsAJLoyKwk1Yikkmvs15Gk+rTT7szNOkXgwhHHCA9WIGraxKWsyqEvi7h1IJIZ0hRWgsGtO0X/3DeBdY04B4hP/20WdI=
jdk:
- oraclejdk8
install: echo 'Run Maven Tests'
script: mvn clean install -Dmaven.javadoc.skip=true -B -V
after_success: mvn deploy --settings .travis/settings.xml -DskipTests -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: bl8WkgflhHOyuAYgDetNBkFSkk638VpEUS8p9US/Ne4osFF1IGOzP3eI6v87fBfmqAB6q901hLT4USLmG2EvL+CBNcurzxrr5isd8M0GBFuwZDlVrWUgIJbHYVzGJl0FWH+TazRXs8+WHM8GfEcKTUwv1g1aNmWSrZppofiePpypc6Ioac02In9OVXuSmmnHKmAD+PIVFPw6Uvs0jkHNzuGyN5sH/0XG5hYDRHqPsUDQ2gGYWApJGK1DZGVH1C0PlFzqg+vPeI4QsQVwrKVbOcSPUM+9a1z5oQpGSgdStK0zc7/EeSCJWZKQ88UgNNdR8dB0Ish+l/brNI2ZitK2l/oQ3LuA9vPLKgjJyQvmD9a6imHH6l4Wu1hSSxvJ7MzozpYhoKlZ5qOM6LstQj2iADf6jKwb/zn7V68tHFPfrp6BoYKp1EwzhMrgz3ExWKTMS09rGhFQKY15p9rC799EuBuVoD8mneTMn1ul62qTCMnQzLIxZYP13PIJonm1dhkodEEDHWmzFQlSsneDjVMilLgIZtVIuh3v8TI7YCW0WWYsqhn20hYCZJ8VdOYHMJceTi54lRbeAoiQM7iXDIkSYtCxSKXpmfrQaasXphi0kqfbkSEgq3HRo5hTQeaU49vBnhYeT2ZFlIzD2lJl6Cjf2t3yKsqm7uL1TANxdcD70BI=
  - secure: N4LD0gsTon+bh5S0kfIvnQPMiTBTXGSqXT7jyHB7E60fH85m44DrruxHDSONcHLRg4PFg3+cRr7v92Yvduwp73Eu9IpUDnB2rocwent38cLjiXf6B2E7HG8R10UVfR4k2yUOU963NLSBCKemCGS+UhNIQDdpCsQHmIYqBeDsm9fXsVv6cc/si/Gpq9IGUdq7zTapRmYceJkj/Uvczy4gzzk+zzvrGn+Al3aGMR8iefFAHCM4DDXdg/de2fvV6N2P7yEnVIYcQCik0hOigJy7IsqI06aDgykRP7RajPg1fbNHkrsGDBcTscopUJID2Nv8sLdPuuQjRo8rrvT7Yu/iQIB1UoLGFUJV5bmY7HEaIblmmXp9dNOwH6MobeKr9Ipdr8wCaUQ09PPEbPafpQgg8Kv8gVUU+AojAGKA0G70Py/lfpkQJNm3zjrixqgq1s3RiHvJ+FBugzMQRoZt1qO+If9ThzfTmyc3EkY7W65kw9Ja9XOCy9GOmzD4y8+JqfMdRWl/FXuEAJMsYjcmU2BaWdt39QQn+vQcH5Z+OOXh+vdJEzJI0wiqPHf7k/GxMBQkpzAh5FlwUR+kjRMsWmNhxTBrao9/P7az3TXREQhvN8nvyR/YCGhQsdEgWqaMRtSBTrhks8pK9R9biKi1lqUCJw8uQ3QbiGEnp5Z4na3ou9s=
