language: java
jdk:
- oraclejdk8
before_install:
  git clone -b travis `git config --get remote.origin.url` target/travis
install:
  echo 'Skipping install step for Maven project'
script:
  mvn clean install
branches:
  except:
    - travis
cache:
  directories:
    - '$HOME/.m2/repository'
