language: java
notifications:
  email: false
  slack:
    secure: k3yyWHpMismLok/4nlnVUObeerA+zZRl/EPjL7rtmbwMB4Q6m4X1lPUjYVyYjXWAtUF5U5VjY5ORTf6pmXS0BnJ4fS/t3n7KJ0n7eL7Rphwq9UGWexXQ3KD2pDLL2Py29KZwprsYfqE+7CLo7To4anC9CY4reLxSXjy8a6WZ70RrBWlrZRYWq9cbxtCTFknHucVY1okApoS2DK8ZTYLnLxmzFXpktciDPHedzGLLJWM03JZSeOxok4N9/xPKHVIIffDcPzCjOyzzpqHEcJ846G2DLfX05kL1Y1kGnlku4MP3Vbx+qiqQKR2P7SL/nGyd2hJgqjKgeVlGX8fo7oZXdRA6iNCAkH9UnJ0KZA1OKA2h0DW3te2hhDsqeJzk0ka2GcvLrrpMlc1BG09Ssr2fbHbPc2UmyIFg7shLgS4b26wK7Fd2ecSvhLmZ/wTwMLlL4iakabaL6d7sFq9KGeCkQodqpzOxlgeltPszqrEpqIPCarMSwILaqedaHVoG4WXuIlPDHt8JnGK6xKnYynBJTvjcIL+w+sx07WD0HnNg2RDibY3bKu52RJf83XN5VWTrXarLGfN3h1lnwT7zsAJLoyKwk1Yikkmvs15Gk+rTT7szNOkXgwhHHCA9WIGraxKWsyqEvi7h1IJIZ0hRWgsGtO0X/3DeBdY04B4hP/20WdI=
jdk:
- oraclejdk8
install: echo 'Build POM and Deploy'
script: mvn clean install -Dmaven.javadoc.skip=true -B -V
after_success: mvn deploy --settings .travis/settings.xml -DskipTests -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: bl8WkgflhHOyuAYgDetNBkFSkk638VpEUS8p9US/Ne4osFF1IGOzP3eI6v87fBfmqAB6q901hLT4USLmG2EvL+CBNcurzxrr5isd8M0GBFuwZDlVrWUgIJbHYVzGJl0FWH+TazRXs8+WHM8GfEcKTUwv1g1aNmWSrZppofiePpypc6Ioac02In9OVXuSmmnHKmAD+PIVFPw6Uvs0jkHNzuGyN5sH/0XG5hYDRHqPsUDQ2gGYWApJGK1DZGVH1C0PlFzqg+vPeI4QsQVwrKVbOcSPUM+9a1z5oQpGSgdStK0zc7/EeSCJWZKQ88UgNNdR8dB0Ish+l/brNI2ZitK2l/oQ3LuA9vPLKgjJyQvmD9a6imHH6l4Wu1hSSxvJ7MzozpYhoKlZ5qOM6LstQj2iADf6jKwb/zn7V68tHFPfrp6BoYKp1EwzhMrgz3ExWKTMS09rGhFQKY15p9rC799EuBuVoD8mneTMn1ul62qTCMnQzLIxZYP13PIJonm1dhkodEEDHWmzFQlSsneDjVMilLgIZtVIuh3v8TI7YCW0WWYsqhn20hYCZJ8VdOYHMJceTi54lRbeAoiQM7iXDIkSYtCxSKXpmfrQaasXphi0kqfbkSEgq3HRo5hTQeaU49vBnhYeT2ZFlIzD2lJl6Cjf2t3yKsqm7uL1TANxdcD70BI=
  - secure: Sle6XmUApovpr4/yFfqINC3dLf19rLYbVEnYeI4E/4azCp/gAD1OD9pLRrUMBCnCF9Hrdjja1ipDZa/u9aiUQyi9fYjpDdY5DV0Cf/4lmdrocHFfIJxNoNcoveT9qFP/nkiS0fwp/BGT9DfsCcAEYY9ivMqqWuYF45LpB7agZyta4tdlcwCV9ujGIZ+Di8b8HeeRovG6FD6fTixGgd5H+4G79k7MlxYakKNbMkG2/ra7VMA0N94r+8A4nqeinLWcv4qa1Zk1yKmvyYYPlcXfjsg5bPCcakf9zR/04U/JuFBhIRa1DpWMLEvCc5vtVtc8pDLrKIqGdKWjESP3t4+Ip1ASUWKDqUjzlhiGEsubB8nRnhRkraHaDhlGJyolDvEMOe9t7pn7ZY3jzUNnjqXi6I+iRX8VnR/YcDqUNVVco0Fo1pCa9ilx3MzVu6pY3sdt8x+Fkvnu2HY53aakMGKRgWQguRUhfHrxPM4tBdMCoP3nMhiYWIzkIbUS2GH2ghWuXYT/SaOvsGGj/PJ7epxc0H8sgFap9au3DuqKaDVuDqx4No0aggXq0F797WFMJx1NhWJhWxlLDHCSgwBd7zYbfCPEBmewfyZ0IvSgXVXlsBrjiwBJH/Q84kXd525NNyztgiqQN+Xbsz5ScOjukzJDFBwvHuZQsD4iDx9jUTTkwoo=
